### ISSUE TITLE
help

### ISSUE THREAD

**Issue by easyLL** [leafgarland/typescript-vim#76]
i have installed with vundle , but the plugin seems unuseful...

**Comment by xangelux** [comment]
No syntax checking or coloring.

**Comment by leafgarland** [comment]
It's difficult for me to know where the problem is. The syntax colouring is just a standard Vim syntax file, assuming the plugin has been correctly installed then you should see your Typescript files (*.ts, *.tsx) being syntax highlighted.

If you load a .ts file, and enter 

```vim
:set filetype
```
You should see Vim respond with `filetype=typescript`, if you don't see that then it is a problem with recognising *.ts, *.tsx.
